[package]
name = "bingmaps"
version = "0.4.0"
description = "API bindings for the Bing Maps v1 HTTP API"
authors = ["Kevin Stenerson <kevin@rapiditynetworks.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rapiditynetworks/bingmaps-rs"
documentation = "https://docs.rs/bingmaps-rs"
keywords = ["bing", "maps", "microsoft", "geocoding", "api"]
categories = ["api-bindings"]
edition = "2018"

[features]
default = ["with-rustls"]
with-rustls = ["hyper-rustls"]
with-openssl = ["hyper-openssl"]

[dependencies]
hyper = "^0.10"
hyper-rustls = { version = "^0.6", optional = true }
hyper-openssl = { version = "^0.2", optional = true }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
serde_urlencoded = "^0.5"
