#[derive(Debug, Deserialize, Serialize)]
pub enum CultureCode {
    #[serde(rename = "af")] Afrikaans,
    #[serde(rename = "am")] Amharic,
    #[serde(rename = "ar-sa")] Arabic, // Saudi Arabia
    #[serde(rename = "as")] Assamese,
    #[serde(rename = "az-Latn")] AzerbaijaniLatin,
    #[serde(rename = "be")] Belarusian,
    #[serde(rename = "bg")] Bulgarian,
    #[serde(rename = "bn-BD")] BanglaBD, // Bangladesh
    #[serde(rename = "bn-IN")] BanglaIN, // India
    #[serde(rename = "bs")] Bosnian, // Latin
    #[serde(rename = "ca")] CatalanSpanish,
    #[serde(rename = "ca-ES-valencia")] Valencian,
    #[serde(rename = "cs")] Czech,
    #[serde(rename = "cy")] Welsh,
    #[serde(rename = "da")] Danish,
    #[serde(rename = "de")] German,
    #[serde(rename = "de-de")] GermanDE, // Germany
    #[serde(rename = "el")] Greek,
    #[serde(rename = "en-GB")] EnglishGB, // United Kingdom
    #[serde(rename = "en-US")] EnglishUS, // United States
    #[serde(rename = "es")] Spanish,
    #[serde(rename = "es-ES")] SpanishES, // Spain
    #[serde(rename = "es-US")] SpanishUS, // United States
    #[serde(rename = "es-MX")] SpanishMX, // Mexico
    #[serde(rename = "et")] Estonian,
    #[serde(rename = "eu")] Basque,
    #[serde(rename = "fa")] Persian,
    #[serde(rename = "fi")] Finnish,
    #[serde(rename = "fil-Latn")] Filipino,
    #[serde(rename = "fr")] French,
    #[serde(rename = "fr-FR")] FrenchFR, // France
    #[serde(rename = "fr-CA")] FrenchCA, // Canada
    #[serde(rename = "ga")] Irish,
    #[serde(rename = "gd-Latn")] ScottishGaelic,
    #[serde(rename = "gl")] Galician,
    #[serde(rename = "gu")] Gujarati,
    #[serde(rename = "ha-Latn")] HausaLatin,
    #[serde(rename = "he")] Hebrew,
    #[serde(rename = "hi")] Hindi,
    #[serde(rename = "hr")] Croatian,
    #[serde(rename = "hu")] Hungarian,
    #[serde(rename = "hy")] Armenian,
    #[serde(rename = "id")] Indonesian,
    #[serde(rename = "ig-Latn")] Igbo,
    #[serde(rename = "is")] Icelandic,
    #[serde(rename = "it")] Italian,
    #[serde(rename = "it-it")] ItalianIT, // Italy
    #[serde(rename = "ja")] Japanese,
    #[serde(rename = "ka")] Georgian,
    #[serde(rename = "kk")] Kazakh,
    #[serde(rename = "km")] Khmer,
    #[serde(rename = "kn")] Kannada,
    #[serde(rename = "ko")] Korean,
    #[serde(rename = "kok")] Konkani,
    #[serde(rename = "ku-Arab")] CentralKurdish,
    #[serde(rename = "ky-Cyrl")] KyrgyzCryillic,
    #[serde(rename = "lb")] Luxembourgish,
    #[serde(rename = "lt")] Lithuanian,
    #[serde(rename = "lv")] Latvian,
    #[serde(rename = "mi-Latn")] Maori,
    #[serde(rename = "mk")] Macedonian,
    #[serde(rename = "ml")] Malayalam,
    #[serde(rename = "mn-Cyrl")] MongolianCryillic,
    #[serde(rename = "mr")] Marathi,
    #[serde(rename = "ms")] Malay, // Malaysia
    #[serde(rename = "mt")] Maltese,
    #[serde(rename = "nb")] Norwegian, // Bokmål
    #[serde(rename = "ne")] Nepali, // Nepal
    #[serde(rename = "nl")] Dutch, // Netherlands
    #[serde(rename = "nl-BE")] DutchBE, // Netherlands
    #[serde(rename = "nn")] NewNorwegian, // Nynorsk
    #[serde(rename = "nso")] SesothoSaLeboa,
    #[serde(rename = "or")] Odia,
    #[serde(rename = "pa")] Punjabi, // Gurmukhi
    #[serde(rename = "pa-Arab")] PunjabiArabic,
    #[serde(rename = "pl")] Polish,
    #[serde(rename = "prs-Arab")] DariArabic,
    #[serde(rename = "pt-BR")] PortugueseBR, // Brazil
    #[serde(rename = "pt-PT")] PortuguesePT, // Portugal
    #[serde(rename = "qut-Latn")] KicheLatin,
    #[serde(rename = "quz")] Quechua, // Peru
    #[serde(rename = "ro")] Romanian, // Romania
    #[serde(rename = "ru")] Russian,
    #[serde(rename = "rw")] Kinyarwanda,
    #[serde(rename = "sd-Arab")] SindhiArabic,
    #[serde(rename = "si")] Sinhala,
    #[serde(rename = "sk")] Slovak,
    #[serde(rename = "sl")] Slovenian,
    #[serde(rename = "sq")] Albanian,
    #[serde(rename = "sr-Cyrl-BA")] SerbianCyrillicBA, // Bosnia and Herzegovina
    #[serde(rename = "sr-Cyrl-RS")] SerbianCyrillicRS, // Serbia
    #[serde(rename = "sr-Latn-RS")] SerbianLatinRS, // Serbia
    #[serde(rename = "sv")] Swedish,
    #[serde(rename = "sw")] Kiswahili,
    #[serde(rename = "ta")] Tamil,
    #[serde(rename = "te")] Telugu,
    #[serde(rename = "tg-Cyrl")] TajikCyrillic,
    #[serde(rename = "th")] Thai,
    #[serde(rename = "ti")] Tigrinya,
    #[serde(rename = "tk-Latn")] TurkmenLatin,
    #[serde(rename = "tn")] Setswana,
    #[serde(rename = "tr")] Turkish,
    #[serde(rename = "tt-Cyrl")] TatarCyrillic,
    #[serde(rename = "ug-Arab")] UyghurArabic,
    #[serde(rename = "uk")] Ukrainian,
    #[serde(rename = "ur")] Urdu,
    #[serde(rename = "uz-Latn")] UzbekLatin,
    #[serde(rename = "vi")] Vietnamese,
    #[serde(rename = "wo")] Wolof,
    #[serde(rename = "xh")] IsiXhosa,
    #[serde(rename = "yo-Latn")] YorubaLatin,
    #[serde(rename = "zh-Hans")] SimplifiedChinese,
    #[serde(rename = "zh-Hant")] TraditionalChinese,
    #[serde(rename = "zu")] IsiZulu,
}
